version: '2'
services:
  esn:
    image: linagora/esn:latest
    container_name: esn
    ports:
     - "8080:8080"
    links:
      - redis
      - mongo
      - sabre
      - elasticsearch
    depends_on:
      - redis
      - mongo
      - sabre
      - elasticsearch
    volumes:
      - ../../config:/var/www/docker/config:ro
    env_file:
      - ../../config/oauth.env
    environment:
      - PROVISION=${PROVISION}
      - CONFIG_DIR=/var/www/docker/config
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=esn_docker
      - MONGO_TIMEOUT=100000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEB_HOST=${DOCKER_IP}
      - WEB_PORT=8080
      - DAV_SERVER_HOST=sabre
      - DAV_SERVER_PORT=80
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_INIT_TIMEOUT=${ELASTICSEARCH_INIT_TIMEOUT}
      - JMAP_SERVER_HOST=${DOCKER_IP}
      - JMAP_SERVER_PORT=1080

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:2.6.5
    command: ["mongod", "--smallfiles"]
    ports:
      - "27017:27017"

  elasticsearch:
    image: linagora/esn-elasticsearch:latest
    ports:
      - "9200:9200"
    environment:
      - ELASTICSEARCH_INIT_TIMEOUT=${ELASTICSEARCH_INIT_TIMEOUT}

  sabre:
    image: linagora/esn-sabre:latest
    ports:
      - "8001:80"
    links:
      - mongo
    environment:
      - SABRE_MONGO_HOST=mongo
      - SABRE_MONGO_PORT=27017
      - ESN_MONGO_HOST=mongo
      - ESN_MONGO_PORT=27017
      - ESN_MONGO_DBNAME=esn_docker
      - MONGO_TIMEOUT=100000
      - ESN_HOST=esn
      - ESN_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  james:
    entrypoint: bash -c "sleep 45; java -Dworking.directory=/root/ -jar james-server.jar"
    image: linagora/james-project:latest
    container_name: esn_james
    ports:
      - "1080:80"
      - "1025:25"
      - "1110:110"
      - "1143:143"
      - "1465:465"
      - "1587:587"
      - "1993:993"
    links:
      - cassandra:cassandra
      - james_elastic:elasticsearch
    depends_on:
      - cassandra
      - james_elastic
    volumes:
      - ../../config/james:/root/conf
      - ../../config/jwt/public:/root/conf/jwt_publickey

  james_elastic:
    image: elasticsearch:1.5.2

  cassandra:
    image: cassandra:2.2.3
